### ISSUE TITLE
Tooltips logic in shops/inventory is broken 

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#162]
When the "Inline detailed information in inventory and shops" setting is enabled, both tooltip and inline text are shown, and there is no tooltip when the setting is disabled.

**Comment by JJM152** [comment]
Yeah, I did that intentionally. I played a lot of this game testing it and I found this to be the most useful configuration (to me).

**Comment by ezsh** [comment]
I disagree with this decision. 1. The tooltip duplicates the inline description. 2. Also played a lot and find the inline mode too noisy and hard for eyes. Therefore, what if I replace the flag with a tri-state(none, tooltip, both) or just split the setting in two (detailed information, detailed information as tooltip)?

**Comment by JJM152** [comment]
> 1. The tooltip duplicates the inline description.

I removed that. It only inlines the status / knowledge effects and shows the detailed description on mouse over. I prefer it this way, sorry if you don't.

**Comment by ezsh** [comment]
Pardon, I have to reopen this again.

> I removed that.

You didn't:

![tooltip-dups](https://user-images.githubusercontent.com/43062025/53285324-796b3280-375f-11e9-9a0b-082256a41adb.png)

3 out of 4 tooltip lines duplicate the text in the details `<div>`.

**Comment by JJM152** [comment]
No, this is why I intended it. I actually in general like the idea so much I'm probably going to make it the default setting.

On the listings I want to display the following
- short description
- (for clothing) Styles | Rank
- Effects

On mouse over I want to display the same as the 'examine' button.

I'm going to update the examine button for gear so that it displays more useful information, particularly in shops, to make purchasing items easier to decide.

**Comment by ezsh** [comment]
OK, I got it, thanks. Still, the exact text duplication in the tooltip is something unusual and it confuses at first. Maybe just a word "Effects: " at the beginning of the last tooltip line (in this example) would resolve that.
