### ISSUE TITLE
Q001b requirement looks unbalanced comparing to other prices

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#34]
For example, high level reels cost approx. 20 000. If player is expected to buy reels, why wouldn't they wait just a bit more and instead of bying two reels buy the freedom?

**Comment by JJM152** [comment]
I definitely agree that there needs to be a pricing rebalance somewhere along the line here as there has been economy creep since I set this (literally the first quest I implemented).

I've tried to address this somewhat by using formula to calculate the price of various items, but I think once the game gets closer to a 1.0 release, then I'll have to take a better look at this.

Closing this for now, but with an eye towards doing a more in depth pass on money later.

**Comment by ezsh** [comment]
Could you, please, at least rise it to ,e.g., 100 000 right away?

**Comment by JJM152** [comment]
I'm actually not sure if I want to inflate this, or if I want to reduce prices on some items, so for now I think I will leave it be as I'm afraid that I'll forget about this later. 

I'll open an issue to be resolved at a future date as a reminder.

**Comment by zeule** [comment]
OK, thanks. To me the other prices look good.
