### ISSUE TITLE
player item objects contain code

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#38]
Hi. I want to further clean up saves and the second thing I want to remove from them (after the code of the Player class) is the code in the `Equipment` and `Wardrobe` objects. While it is simple to refactor that and remove the code, I would like to ask whether it serves a purpose, invisible to me? Thanks.

**Comment by JJM152** [comment]
There's no invisible purpose here, just perhaps a lot of dependencies in other files because of the current implementation which will be hard to clean up.  I did something similar with the NPC's (used to be stored as objects in the player class) and put a facade around them, see GetNPC(str) in Player.js, to convert the stored dictionary data into an object.

The biggest issue I think is that a lot of inventory management and UI screens may need to be rewritten. I'm not sure how diligent I was at using methods vs. manipulating the data structures directly.

Maybe even a sensible refactor of some of these methods might be in order?

**Comment by ezsh** [comment]
Thanks for the reply. I'll try my best to minimise changes to the item classes and the widgets/UI elements.
